version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:10.15.0

commands:
  install_dependencies:
    ...
  set_deploy_key:
    description: Sets the ssh key for project access
    steps:
      - add_ssh_keys:
          fingerprints:
            - '7f:21:19:eb:46:d1:8a:49:1a:f5:10:2f:b9:28:d6:65'

jobs:
  ...
    deploy:
      executor: node
      steps:
        - set_deploy_key
        - checkout
        - install_dependencies
        - run:
            name: Deploy
            command: yarn deploy

workflows:
  deploy:
    jobs:
      - lint:
          filters:
            branches:
              ignore: 'gh-pages'
      - test:
          filters:
            branches:
              ignore: 'gh-pages'
      - deploy:
          filters:
            branches:
              only: master
          requires:
            - lint
            - test
