version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:10.15.0

jobs:
  install:
    steps:
      - checkout
      - restore_cache:
            keys:
              - yarn-cache-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: yarn-cache-{{ checksum "yarn.lock" }}

  eslint:
    steps:
      - run: yarn eslint-all

  stylelint:
    steps:
      - run: yarn stylelint-all

  typecheck:
    steps:
      - run: yarn typecheck

  test:
    steps:
      - run: yarn test

workflows:
  jobs:
    - install:
        filters:
          branches:
            ignore:
              - master
    - eslint:
        requires:
          - install
    - stylelint:
        requires:
          - install
    - typecheck:
        requires:
          - install
    - test:
        requires:
          - install
