version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:10.15.0

commands:
  install_dependencies:
    ...
  set_deploy_key:
    description: Sets the ssh key for project access
    steps:
      - add_ssh_keys:
          fingerprints:
            - '7f:21:19:eb:46:d1:8a:49:1a:f5:10:2f:b9:28:d6:65'

jobs:
install:
  steps:
    - checkout
    - run: yarn install
  eslint:
    steps:
      - run: yarn eslint-all
  stylelint:
    steps:
      - run: yarn stylelint-all
  typecheck:
    steps:
      - run: yarn typecheck
  test:
    steps:
      - run: yarn test

workflows:
  jobs:
    - lint:
        requires:
          - install
    - typecheck:
        requires:
          - install
    - test:
        requires:
          - install
