version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:10.15.0

references:
  workspace_root: &workspace_root
    /home/circleci/catD

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

jobs:
  install:
    docker:
      - image: circleci/node:10.15.0
    steps:
      - checkout
      - restore_cache:
            keys:
              - yarn-cache-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: yarn-cache-{{ checksum "yarn.lock" }}

  lint:
    docker:
      - image: circleci/node:10.15.0
    steps:
      - *attach_workspace
      - run: yarn eslint-all
      - when:
        condition: eslint
        steps:
          - run: echo "preinstall"
      - unless:
        condition: << parameters.preinstall-foo >>
        steps:
          - run: echo "don't preinstall"      

  style:
    docker:
      - image: circleci/node:10.15.0
    steps:
      - *attach_workspace
      - run: yarn stylelint-all

  typecheck:
    docker:
      - image: circleci/node:10.15.0
    steps:
      - *attach_workspace
      - run: yarn typecheck

  test:
    docker:
      - image: circleci/node:10.15.0
    steps:
      - *attach_workspace
      - run: yarn test

workflows:
  jobs:
    - install:
        filters:
          branches:
            ignore:
              - master
    - lint:
        requires:
          - install
    - style:
        requires:
          - install
    - typecheck:
        requires:
          - install
    - test:
        requires:
          - install
